# Generated by Django 5.2.7 on 2025-12-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
