# Generated by Django 5.2.7 on 2025-12-30 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_hotel_is_paid_delete_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
